### ISSUE TITLE
Category Labels for Semantics

### ISSUE THREAD

**Issue by chenwydj** [facebookresearch/habitat-api#221] opened 2019-10-02 00:01 UTC
## ❓ Questions and Help

For mp3d there are 40 semantic categories. I can see that the color of the semantic segmentation is based on `semantic_img.putdata((semantic_obs.flatten() % 40).astype(np.uint8))` in [this demo](https://github.com/facebookresearch/habitat-api/blob/e0d4056180fea3238a51cec1b2fe47c09a8f08a2/docs/pages/habitat-sim-demo.rst).

Could you provide the meanings of the semantics, i.e. the category label for each semantic index? I found the indices loaded by the SEMANTIC_SENSOR do not match the [original mp3d labels](https://github.com/niessner/Matterport/blob/master/metadata/category_mapping.tsv).

Thank you very much!

**Comment by erikwijmans** [comment] 2019-10-03 14:49
I believe this is a duplicate of https://github.com/facebookresearch/habitat-sim/issues/263. Closing

**Closed by erikwijmans** 2019-10-03 14:49 UTC
